config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products do
  resources :reviews, only: [:show, :create, :destroy]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews

  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  has_many :products, through: :reviews
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, only: [:create, :destroy]
  before_filter :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to products_path, notice: 'Review created successfully'
    else
      render 'products/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minas_helper.rb
module MinasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>

      <p class="userinfo">
        <% if current_user %>
          Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
        <% else %>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Your Product</h1>
<p>
  <%= link_to "Back", @product %>
</p>

<%= form_for @product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/index.html.erb
<h1>Products Index</h1>
<%= link_to "New Product", "/products/new" %>

<% @products.each do |product| %>
  <p><b><%= link_to product.name.capitalize, product %></b> - <%= product.description.capitalize %></p>
  <p>$ <%= product.formatted_price %></p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= link_to "Back to Products Index", products_url %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete this product?"} %>

<p><b><%= @product.name.capitalize %></b> - <%= @product.description.capitalize %></p>
  <p>$ <%= @product.formatted_price %></p>

<h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em>by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

  <% if current_user %>
    <h4>New Review</h4>

    <%= form_for([@product, @review]) do |f| %>
      <% if @review.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

          <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

  <% else %>
    <p>Please <%= link_to "Log in", new_session_path %> to add a review.</p>
  <% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_message.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>